$(function() {
  	$('.anime0').animepng({
  		src:'./images/char_sandogasa.png',
  		width:32,
  		height:48,
  		fps:4
  	});
  	$('.anime1').animepng({
  		src:'./images/char_sandogasa.png',
  		posy:48,
  		width:32,
  		height:48,
  		fps:8
  	});
  	$('.anime2').animepng({
  		src:'./images/char_sandogasa.png',
  		posy:96,
  		width:32,
  		height:48,
  		fps:16
  	});
  	$('.anime3').animepng({
  		src:'./images/char_sandogasa.png',
  		posy:144,
  		width:32,
  		height:48,
  		fps:32
  	});
});
